# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVCqjtgwu2gAFiJiUWmFYSUEDTIHhZ_a
"""

from mininet.topo import Topo


class MyTopo( Topo ):
    "2 host 2 switch 2 host 1 switch 2 host custom topology"

    def __init__( self ):
        "Create custom topo."

        # Initialize topology
        Topo.__init__( self )

        # Add hosts and switches
        leftHosth1 = self.addHost( 'h1' )
        leftHosth2 = self.addHost( 'h2' )
        leftSwitch = self.addSwitch( 's1' )

        downHosth3 = self.addHost( 'h3' )
        downHosth4 = self.addHost( 'h4' )
        downSwitch = self.addSwitch( 's3' )

        rightHosthh5 = self.addHost( 'h5' )
        rightHosthh6 = self.addHost( 'h6' )
        rightSwitch = self.addSwitch( 's2' )

        # Add links
        self.addLink( leftHosth1, leftSwitch )
        self.addLink( leftHosth2, leftSwitch )

        self.addLink( downHosth3, downSwitch )
        self.addLink( downHosth4, downSwitch )

        self.addLink( rightHosthh5, rightSwitch )
        self.addLink( rightHosthh6, rightSwitch )

        self.addLink(leftSwitch, downSwitch)
        self.addLink(downSwitch, rightSwitch)

topos = { 'mytopo': ( lambda: MyTopo() ) }